### ISSUE TITLE
using uwrmaxsat as a shared library

### ISSUE THREAD

**Issue by fg-dev** [marekpiotrow/UWrMaxSat#13]
I would like to use uwrmaxsat as a shared library, but I am confused about how to proceed since there is no global header file available.

Could you please provide a small example that explains how to do this?

Best regards,

**Comment by marekpiotrow** [comment]
You can use the IPAMIR interface with the header file ipamir.h. The general description of the interface you can find, for example, in the paper: Incremental Maximum Satisfiability by Andreas Niskanen, Jeremias Berg and Matti Järvisalo. See also: https://maxsat-evaluations.github.io/2022/incremental.html Examples of its usage are at https://bitbucket.org/coreo-group/ipamir/src/master/

Best regards
