### ISSUE TITLE
Infinite loop under specific circumstances

### ISSUE THREAD

**Issue by grechnik** [marekpiotrow/UWrMaxSat#3]
Environment: the latest commit (17221278d1f988b9b26414d34567d4ba010fa794), COMinisatPs, no MAXPRE, no SCIP. The built-in preprocessing will also be disabled by command line options.

Preparation: to keep the example small, decrease the budget in `core_minimization` and `optimize_last_constraint`:
```
$ git diff
diff --git a/MsSolver.cc b/MsSolver.cc
index 6029e53..08dcff0 100644
--- a/MsSolver.cc
+++ b/MsSolver.cc
@@ -112,7 +112,7 @@ void core_minimization(SimpSolver &sat_solver, Minisat::vec<Lit> &mus)
 {
     int last_size = mus.size();

-    sat_solver.setConfBudget(1000);
+    sat_solver.setConfBudget(3);
     int verb = sat_solver.verbosity; sat_solver.verbosity = 0;
     for (int i = 0; last_size > 1 && i < last_size; ) {
         Lit p = mus[i];
@@ -303,7 +303,7 @@ void MsSolver::optimize_last_constraint(vec<Linear*>& constrs, Minisat::vec<Lit>
     int verb = sat_solver.verbosity; sat_solver.verbosity = 0;
     bool found = false;

-    sat_solver.setConfBudget(1000);
+    sat_solver.setConfBudget(3);
     if (satSolveLimited(assump_ps) == l_False) {
         for (int i=0; i < sat_solver.conflict.size(); i++)
             if (assump_ps.last() == ~sat_solver.conflict[i]) { found = true; break;}
```
It is possible to do the same with the original budget, but that would require a much larger example. After all, these constants should only influence the performance, not the correctness.

The file `hang.wcnf`:
```
p wcnf 20 42 10000
10000 1 2 3 4 0
10000 3 5 0
10000 4 5 0
10000 1 12 13 0
10000 1 12 -13 0
10000 1 -12 13 0
10000 1 -12 -13 0
10000 -1 12 -13 0
10000 -1 -12 13 0
10000 -1 -12 -13 0
10000 2 12 13 0
10000 3 12 13 0
10000 3 12 -13 0
10000 3 -12 13 0
10000 3 -12 -13 0
10000 4 12 13 0
10000 4 12 -13 0
10000 4 -12 13 0
10000 4 -12 -13 0
10000 17 16 15 0
10000 17 16 -15 0
10000 17 -16 15 0
10000 17 -16 -15 0
10000 -17 16 15 0
10000 -17 16 -15 0
10000 -17 -16 -15 0
10000 20 19 18 0
10000 20 19 -18 0
10000 20 -19 18 0
10000 20 -19 -18 0
10000 -20 19 18 0
10000 -20 19 -18 0
10000 -20 -19 -18 0
1 -1 0
1 -2 0
1 -3 0
1 -4 0
1 -5 0
1 -6 0
1 -7 0
1 -8 0
1 -9 0
```
(we want to minimize the number of `true` assignments to `x1`,...,`x9`, not-immediately-obvious conditions force `x1=x2=x3=x4=true`).

Build with the patch and run: `build/release/bin/uwrmaxsat -no-pre -no-ms-pre -v3 hang.wcnf`.
Expected result: the example is small and should be instantly solved (`o 4`).
Actual result: the verbose logging `-v3` provides an infinite stream of
```
c ======================[ COMiniSatPS search starting  ]========================
c Lower bound  = 2, assump. size = 6, stratif. level = 0 (cls: 0, wght: 0)
c ======================[ COMiniSatPS search starting  ]========================
c Lower bound  = 2, assump. size = 6, stratif. level = 0 (cls: 0, wght: 0)
```

What is going on:

_Iteration 1._ The SAT solver is called with assumptions `x1=...=x9=false`; the propagation immediately notices the first clause and returns that `x1|x2|x3|x4` should be `true`.

_Core minimization 1._ The budget of 3 conflicts is spent on figuring out that `x20=x19=true`, `x18=false` without changing the core.

_Constraint generation 1._ The condition `x1+x2+x3+x4>1` is encoded as a new variable `y1`; constraint optimization spents the budget of 3 conflicts on figuring out that `x17=x16=true`, `x15=false` without changing any important stuff.

_Iteration 2._ The SAT solver is called with assumptions `x5=...=x9=y1=false`; the propagation of `x5=false` deduces that `x3=x4=true` so `x5=false` implies `x1+x2+x3+x4>1` and is inconsistent with `y1=false`. So far so good.

_Core minimization 2_, where things are starting to get weird. The SAT solver is called with one assumption `x5=false`, propagates it to `x3=x4=true` and starts trying new literals; after 3 conflicts the solver deduces that `x1=x2=true` independently of the assumption, so `y1` should be `true` independently of the assumption, and the assumption itself is satisfiable. Then, the SAT solver is called with one assumption `y1=false`, **but the budget in core_minimization is set once for all solves, so the second call operates on zero budget and immediately returns Undef** even though `value(y1) == l_True`. So the minimized core still consists of two literals, `y1=false` and `x5=false`.

_Constraint generation 2_. Two new conditions are encoded, `x1+x2+x3+x4>2` and `y1+x5>1`. `addConstr` (via `PbSolver::normalizePb`) notices that `value(y1) == l_True`, so the second condition is equivalent to `x5=true`; `PbSolver::normalizePb` immediately generates a new variable `y2`, a clause `~x5|~y2` (so `y2` actually encodes `y1+x5<=1`) and returns `false` as an indicator that the linear condition is not present anymore. The first condition is "lowered" into SAT clauses by the call to `convertPbs` that happens after `addConstr`, so the associated variable `y3` is **numerically higher** than `y2`. However, the main loop in `MsSolver::maxsat_solve` appends these variables to `assump_ps` in the order `y3` and then `y2`, so **`assump_ps` becomes unordered**.

_Iteration 3._ The SAT solver is called with assumptions `x6=...=x9=y3=false`, `y2=true`. This time, it figures out that `x1=x2=x3=x4=true`, so `y3` must be `true` and returns just one literal as a core. Core minimization does nothing. The further processing tries to find `y3` in `assump_ps`. **`Sort::bin_search` fails because `assump_ps` is not ordered anymore.** I haven't checked what exactly happens after that, because the state is clearly broken at this point, it seems that the search is just restarted in the infinite loop where nothing important is changed.

**Comment by marekpiotrow** [comment]
Thank you for the detailed analysis and the key observation that the vector assump_ps can become unordered in a certain circumstances. I have fixed this by adding a loop that corrects the order (see the commit 8d6c3bd).

**Comment by grechnik** [comment]
Yes, that fixes the issue.
