### ISSUE TITLE
.so library

### ISSUE THREAD

**Issue by DennisYurichev** [marekpiotrow/UWrMaxSat#4]
Marek,

I have a hard time in compiling .so library.
Too much dependencies...
Can I ask you for instructions, or, already compiled .so for linux x64?

Basically, I only want to call IPAMIR functions from Python code.

TIA!

**Comment by DennisYurichev** [comment]
Thanks for your reply.

And so I did. I only changed scipoptsuite-8.0.4 and scipoptsuite-8.0.0 everywhere to scipoptsuite-8.1.0, because newer version I have.

Now MWE:
```
 % pwd
/home/dropbox/tmp/1/UWrMaxSat/build/dynamic/lib
dropbox@centrolit ~/tmp/1/UWrMaxSat/build/dynamic/lib
 % ls
libuwrmaxsat.so  libuwrmaxsat.so.1  libuwrmaxsat.so.1.3.5
dropbox@centrolit ~/tmp/1/UWrMaxSat/build/dynamic/lib
 % python3
...
>>> import ctypes
>>> ctypes.CDLL("./libuwrmaxsat.so.1.3.5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./libuwrmaxsat.so.1.3.5: undefined symbol: _ZTIN11COMinisatPS10SimpSolverE
>>>
```

COMinisatPS is to be linked with this .so as well?

**Comment by marekpiotrow** [comment]
There was an error in the Makefile rule for the dynamic library. I have just pushed a corrected version of the Makefile. In addition, the static libraries should be compiled with the -fPIC option.  That means that:
(1) The SAT solver library should be made with the command: CFLAGS=-fPIC MROOT=.. make libr
(2) The MaxPre Makefile should be modified with: sed -i 's/-g/-fPIC -D NDEBUG/' src/Makefile
(3) At the beginning of scipoptsuite-8.1.0/scip/src/CMakeLists.txt the following line should be added:
         set(SCIP_COMP_OPTIONS ${SCIP_COMP_OPTIONS} -fPIC)

These steps should correct the errors with loading the library in Python. I am not familiar with ctypes in Python, so please write me any further problem with your project.

Marek

**Comment by DennisYurichev** [comment]
Thanks, that works!
